### ISSUE TITLE
About evaluation

### ISSUE THREAD

**Issue by madajie9** [qzp2018/AnyTrans#1]
Dear Author,
   Thank you very much for sharing your great work. It's very helpful for me to read the paper and learn about a complete process for image text translating and re-rendering.

   Large model for translating in your code is Qwen series LLM, not VLM (in paper, the best score in table 2 is generated by VLM qwen-vl-max)
   Could you please provide (1) VLM calling code, and (2) BLEU and COMET calculating code, especially the N value in BLEU and model name used in COMET?  These two information will be very helpful for evaluation on the dataset you shared and reproduce the best score.

Best wishes~

**Comment by qzp2018** [comment]
Hi  1)VLM calling code is simply like using LLM code, but change the model name and add image's path, you can refer to the official example of Alibaba Cloud 2) BLEU and COMET calculating are using default config,  by using command-line commands, the N value in BLEU is 1, and COMET is using the official Quick Installation. 
However, our evaluation process is very cumbersome, and it is highly recommended that you re-evaluate it according to your own needs when using our datasets.

**Comment by madajie9** [comment]
Thank you very much for replying me~
I got the point
(1) the usage of VLM is same as LLM but add image as input
(2) BLEU N=1
(3) COMET uses command-line, which means that the model is default one:
https://github.com/Unbabel/COMET
Default Model: [Unbabel/wmt22-comet-da](https://huggingface.co/Unbabel/wmt22-comet-da)
